### PR TITLE
🐼 Add pandas DataFrame render style

### LINKED ISSUE #47: Improve style effect for DataFrame rendering in React Node with jupyter output
### Context

When I used sphinx-book-theme, the pandas DataFrame type output is rendered pretty well. However, in the React Node with jupyter output, especially for multi-index DataFrame, the effect is not fully desired. We can try to align with the sphinx version for myst-theme to improve user experience.

---------------------------------

### Proposal

_No response_

### Tasks and updates

_No response_

### PR DESCRIPTION
**Pull request by GYHHAHA**
Now the render result is aligned with sphinx-book-theme. Looks better!
- close #47 

---------------------------------

### CODE REVIEW

**Comment by stevejpurves** [comment]
@GYHHAHA to understand the context, are you using the myst-theme as-is with book-theme or article-theme or are you developing your own theme?

**Comment by GYHHAHA** [comment]
@stevejpurves I'm doing my own theme. But these two figures are produced with book-theme by myst-cli.

**Comment by rowanc1** [comment]
This looks great! 🚀 Thank you for your help! :)

**Comment by stevejpurves** [comment]
ok it's probably good to get this in and align with the dataframe specific styles here. Note that over here: https://github.com/executablebooks/myst-book-theme/pull/4/files

We're loading additional stylesheets from `thebe` which should be in here already really, that will align styling of juptyer outputs to how they are rendered in juptyerlab, and has an impact on the table rendering.

image

But that is not dataframe specific, it applied to tables outputs generally.

@GYHHAHA you may want to include those styles in your theme too

**Comment by GYHHAHA** [comment]
@stevejpurves This is absolutely fine. If thebe style sheet has already decided to control the table render, you can revert my change in jupyter.css in your pr draft to avoid confusion for the later contributors.

**Pull request merged**
