### PR TITLE
📖  Add links to the MyST Theme documentation

### PR DESCRIPTION
**Pull request by choldgraf**
Adds a few links to the theme documentation in the README, in the hopes that this makes them easier to discover.

### CODE REVIEW

**Comment by rowanc1** [comment]
🚀

**Comment by choldgraf** [comment]
@rowanc1 I tagged @agoose77 just because he was the one affected by this initially, but I think it's fine if you just want to merge!

Probably best to have a future team conversation about this, but personally I'd prefer that we adopt a liberal merge policy like:

> anybody should merge a PR if they think it's ready to go unless explicitly stated otherwise by the author

In my opinion it's more important that we can fluidly iterate than if we get the changes perfect the first time. I know others might want more mechanisms to ensure quality control, but just stating where I'm at there :-)

**Comment by agoose77** [comment]
@choldgraf I'd be tempted to scope that to docs, rather than all PRs given the amount of domain-specific knowledge that I know I need to continue to develop.

**Comment by rowanc1** [comment]
Yeah - I held off merging because you tagged @agoose77, I think we can just keep channels open, use our best discretion, and aim to get things merged as fast as we can.

**Pull request merged**
