### PR TITLE
‼️ Show errors in embedded notebooks

### PR DESCRIPTION
**Pull request by stevejpurves**
Add a component and logic that will catch and show "off page" notebook errors.

This PR adds an error tray using a jupyter output error to properly display the callback:

image

### CODE REVIEW

**Comment by stevejpurves** [comment]
@rowanc1 currently this is displayed at the top of the article. With some more work tracking cell id's etc we could probably get it to display under the figure that triggered it, but perhaps it's better in a toaster/popup that gets the reader's attention but can be dismissed?

**Comment by rowanc1** [comment]
Nice, will take a look!

**Comment by rowanc1** [comment]
I can't get this to work? This is with thebe-lite:

image

**Comment by stevejpurves** [comment]
do you this is is good to go as an increment, and we improve positioning in a separate PR?

**Comment by rowanc1** [comment]
Yep! Just waiting for tests to go green!

**Pull request merged**
