### PR TITLE
empty frontmatter title should not make h1

### PR DESCRIPTION
**Pull request by tavin**
Fixes a case that may have been uncommon but is more likely when https://github.com/executablebooks/mystjs/issues/281 is done.

### CODE REVIEW

**Comment by rowanc1** [comment]
This is awesome @tavin, thanks so much for the various contributions around this!!

I will look at this in my afternoon (in about 4hrs) and get it out!!

**Comment by tavin** [comment]
Cheers @rowanc1 this one should be the least debatable of the PRs I have opened :)

**Comment by rowanc1** [comment]
Just working to get back to this, will get to it today!!

**Comment by rowanc1** [comment]
Merging this in. :) Thank you.

**Pull request merged**
