### PR TITLE
:wrench: Fix positioning of secondary sidebar when scrolling

### PR DESCRIPTION
**Pull request by agoose77**
@rowanc1 brought this to my attention somewhere.

### CODE REVIEW

**Comment by agoose77** [comment]
Huh, testing this was difficult. I'm not sure why setting `top` via the JSX `style` attribute behaves as expected, but setting the same value via tailwind classes does not. I assume it's a priority thing. In any case, I noticed that we lost the `useThemeTop` logic. I didn't see why we added that to begin with, but I assume it's all in the effort to be more consistent.

I've just eye-balled the vertical position thereafter; the TOC is using flex, whereas the secondary nav container is block display. So, it's approximate.

**Comment by stevejpurves** [comment]
@agoose77 how were you setting the tailwind class exactly?

**Comment by agoose77** [comment]
> @agoose77 how were you setting the tailwind class exactly?

In the `className` attribute of the JSX.

**Comment by stevejpurves** [comment]
@agoose77 ok I just wondered if you were using an arbitrary value pattern? like:

```{`p-2 some-class top-[${top}px] border ...`}```

As tailwind cannot compile that to a class name at build time, in those circumstance using style is best

**Comment by stevejpurves** [comment]
book-theme looks great 👍🏼 

article-theme looks worse though?

image

It's not aligned with content top or anything else.

while previously it looks good alignment wise

image

**Comment by agoose77** [comment]
Hmm, I see your point. Maybe let's revert that; I'll check the rationale when next at my pc.

**Comment by stevejpurves** [comment]
Latest:

book-theme
image

article-theme
image

**Review by stevejpurves — APPROVED** [review]
some tweaks and more eyeballing but looks ok!

**Pull request merged**
